/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cic.view;

import cic.controller.CAuthentication;
import cic.entity.Role;

/**
 *
 * @author alfredo
 */
public class CicPageWithMenu extends CicPage {

    /**
     * Creates new form CicPageWithMenu
     */
    public CicPageWithMenu() {
        initComponents();
        CAuthentication auth=CAuthentication.getInstance();
        Role role=auth.getEmployeeRole();
        if(role==Role.EMPLOYEE){
            this.UnclassifiedClaimsMenuItem.setVisible(false);
            this.ClassifiedClaimsMenuItem.setVisible(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        RegisterClaimMenuItem = new javax.swing.JMenuItem();
        UnclassifiedClaimsMenuItem = new javax.swing.JMenuItem();
        ClassifiedClaimsMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Actions");

        RegisterClaimMenuItem.setText("Register Claim");
        RegisterClaimMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterClaimMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(RegisterClaimMenuItem);

        UnclassifiedClaimsMenuItem.setText("Unclassified Claims");
        UnclassifiedClaimsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnclassifiedClaimsMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(UnclassifiedClaimsMenuItem);

        ClassifiedClaimsMenuItem.setText("Classified Claims");
        ClassifiedClaimsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassifiedClaimsMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(ClassifiedClaimsMenuItem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterClaimMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterClaimMenuItemActionPerformed
    RegisterClaimPage regPag= new RegisterClaimPage();
    regPag.setVisible(true);        // TODO add your handling code here:
    this.dispose();
        
    }//GEN-LAST:event_RegisterClaimMenuItemActionPerformed

    private void UnclassifiedClaimsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnclassifiedClaimsMenuItemActionPerformed
        // TODO add your handling code here:
        UnclassifiedClaimsPage ucp=new UnclassifiedClaimsPage();
        ucp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UnclassifiedClaimsMenuItemActionPerformed

    private void ClassifiedClaimsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassifiedClaimsMenuItemActionPerformed
        // TODO add your handling code here:
        ClassifiedClaimsPage ucp=new ClassifiedClaimsPage();
        ucp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ClassifiedClaimsMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CicPageWithMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CicPageWithMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CicPageWithMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CicPageWithMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CicPageWithMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ClassifiedClaimsMenuItem;
    private javax.swing.JMenuItem RegisterClaimMenuItem;
    private javax.swing.JMenuItem UnclassifiedClaimsMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
