/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cic.view;

import cic.controller.CClaimManager;
import cic.entity.Claim;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alfredo
 */
public class HistoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HistoryJPanel
     */
    
    private String ssn;
    private DefaultTableModel modelPrevious;
    
    /**
     * for acceptance test
     */
    
   
    
    
    public HistoryJPanel() {
        initComponents();
        modelPrevious=(DefaultTableModel)this.previousHistoryTable.getModel();
        
    }
    
    public void updateHistoryTable(Claim currentClaim){
        
        
        
        
        
        //update prev history table
        Claim c=currentClaim;
        
        this.UserSsnLabel.setText(c.getOwnerSsn());
        
        while (modelPrevious.getRowCount()>0){
            modelPrevious.removeRow(0);
        }
        ArrayList<Claim> prevClaims=CClaimManager.getInstance().getHistoryOfUser(c.getOwnerSsn());
        for(Claim claim:prevClaims){
            if(claim!=currentClaim){
              modelPrevious.addRow(new Object[]{claim.getId().toString(), claim.getDescription(),
                 claim.getCostOfDamage(), claim.getPriceOfCar(),claim.getComplexity().toString(),
                 claim.getFinalDecision().toString()
              });
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        previousHistoryTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        UserSsnLabel = new javax.swing.JLabel();

        previousHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Description", "Cost Of Damage", "Price Of car", "Complexity", "Decision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(previousHistoryTable);

        jLabel1.setText("Table of history of previous accidents for user: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserSsnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(UserSsnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(292, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(61, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserSsnLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable previousHistoryTable;
    // End of variables declaration//GEN-END:variables
}
