/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cic.view;

import cic.controller.CClaimManager;
import cic.entity.Claim;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alfredo
 */
public class UnclassifiedClaimsPage extends CicPageWithMenu {

    
    private ArrayList<Claim> claims;
    
    DefaultTableModel model;
    
    private Claim currentClaim;
    /**
     * Creates new form UnclassifiedClaimsPage
     */
    public UnclassifiedClaimsPage() {
        initComponents();
        CClaimManager contr = CClaimManager.getInstance();
        claims=contr.getUnclassifiedClaims();
        model=(DefaultTableModel)this.ClaimsTable.getModel();
        
        
        for(Claim claim:this.claims){
            model.addRow(new Object[]{claim.getId().toString(), claim.getOwnerSsn(), claim.getDescription()});
        }
        
        
         ListSelectionModel cellSelectionModel = this.ClaimsTable.getSelectionModel();
         cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         
         cellSelectionModel.addListSelectionListener(
                 new ListSelectionListener() {
                   public void valueChanged(ListSelectionEvent e) {
                        int index=ClaimsTable.getSelectedRow();
        
                       currentClaim=claims.get(index);
                       updateLowerPart();
      }

    });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ClaimsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        IdLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();
        SimpleButton = new javax.swing.JButton();
        ComplexButton = new javax.swing.JButton();
        historyJPanel = new cic.view.HistoryJPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ClaimsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ssn", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ClaimsTable);

        jLabel1.setText("ID");

        IdLabel.setText("-------------------------");

        jLabel3.setText("Description");

        DescriptionLabel.setText("-------------------------");

        SimpleButton.setText("Mark as simple");
        SimpleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpleButtonActionPerformed(evt);
            }
        });

        ComplexButton.setText("Mark as complex");
        ComplexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComplexButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdLabel)
                    .addComponent(DescriptionLabel))
                .addGap(0, 247, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(SimpleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ComplexButton)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(historyJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IdLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(historyJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SimpleButton)
                    .addComponent(ComplexButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimpleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpleButtonActionPerformed
        // TODO add your handling code here:
        this.currentClaim.classifyAsSimple();
        UnclassifiedClaimsPage newPage=new UnclassifiedClaimsPage();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SimpleButtonActionPerformed

    private void ComplexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComplexButtonActionPerformed
        this.currentClaim.classifyAsComplex();
        UnclassifiedClaimsPage newPage=new UnclassifiedClaimsPage();
        newPage.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ComplexButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnclassifiedClaimsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnclassifiedClaimsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnclassifiedClaimsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnclassifiedClaimsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnclassifiedClaimsPage().setVisible(true);
            }
        });
    }
    
    private void updateLowerPart(){
        
        //update labels
       Claim c=currentClaim;
       this.IdLabel.setText(c.getId().toString());
       this.DescriptionLabel.setText(c.getDescription());
       this.historyJPanel.updateHistoryTable(currentClaim);
        
        
        
      
        
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ClaimsTable;
    private javax.swing.JButton ComplexButton;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JButton SimpleButton;
    private cic.view.HistoryJPanel historyJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
